"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

import requests as requests_http
from . import utils
from leapmlapi.models import operations

class Projects:
    _client: requests_http.Session
    _security_client: requests_http.Session
    _server_url: str
    _language: str
    _sdk_version: str
    _gen_version: str

    def __init__(self, client: requests_http.Session, security_client: requests_http.Session, server_url: str, language: str, sdk_version: str, gen_version: str) -> None:
        self._client = client
        self._security_client = security_client
        self._server_url = server_url
        self._language = language
        self._sdk_version = sdk_version
        self._gen_version = gen_version
        
    def projects_controller_remove(self, request: operations.ProjectsControllerRemoveRequest, security: operations.ProjectsControllerRemoveSecurity) -> operations.ProjectsControllerRemoveResponse:
        r"""Delete a Project"""
        base_url = self._server_url
        
        url = utils.generate_url(operations.ProjectsControllerRemoveRequest, base_url, '/api/v1/projects/{projectId}', request)
        
        
        client = utils.configure_security_client(self._client, security)
        
        http_res = client.request('DELETE', url)
        content_type = http_res.headers.get('Content-Type')

        res = operations.ProjectsControllerRemoveResponse(status_code=http_res.status_code, content_type=content_type, raw_response=http_res)
        

        return res

    