"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import dateutil.parser
from ..shared import modelentity as shared_modelentity
from ..shared import weightsentity as shared_weightsentity
from dataclasses_json import Undefined, dataclass_json
from datetime import datetime
from enum import Enum
from leapmlapi import utils
from marshmallow import fields

class ModelVersionEntityStatusEnum(str, Enum):
    QUEUED = "queued"
    PROCESSING = "processing"
    FINISHED = "finished"
    FAILED = "failed"


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class ModelVersionEntity:
    r"""The model training has been successfully queued."""
    
    created_at: datetime = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('createdAt'), 'encoder': utils.datetimeisoformat(False), 'decoder': dateutil.parser.isoparse, 'mm_field': fields.DateTime(format='iso') }})  
    id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('id') }})  
    model: shared_modelentity.ModelEntity = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('model') }})  
    status: ModelVersionEntityStatusEnum = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('status') }})  
    weights: shared_weightsentity.WeightsEntity = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('weights') }})  
    