"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses


@dataclasses.dataclass
class SchemeBearer:
    
    authorization: str = dataclasses.field(metadata={'security': { 'field_name': 'Authorization' }})  
    