"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import bodydtowithurl as shared_bodydtowithurl
from ..shared import controlentity as shared_controlentity
from typing import Optional


@dataclasses.dataclass
class ControlControllerCreateWithURLSecurity:
    
    bearer: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'http', 'sub_type': 'bearer', 'field_name': 'Authorization' }})
    

@dataclasses.dataclass
class ControlControllerCreateWithURLRequest:
    
    body_dto_with_url: shared_bodydtowithurl.BodyDtoWithURL = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    model_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'modelId', 'style': 'simple', 'explode': False }})
    r"""The ID of the model to use for the image generation."""
    

@dataclasses.dataclass
class ControlControllerCreateWithURLResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    control_entity: Optional[shared_controlentity.ControlEntity] = dataclasses.field(default=None)
    r"""The newly created job."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    