"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import remixjob as shared_remixjob
from typing import Optional


@dataclasses.dataclass
class ControlControllerFindOneSecurity:
    
    bearer: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'http', 'sub_type': 'bearer', 'field_name': 'Authorization' }})
    

@dataclasses.dataclass
class ControlControllerFindOneRequest:
    
    model_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'modelId', 'style': 'simple', 'explode': False }})
    r"""The ID of the model that the job belongs to."""
    remix_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'remixId', 'style': 'simple', 'explode': False }})
    r"""The ID of the job to retrieve."""
    

@dataclasses.dataclass
class ControlControllerFindOneResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    remix_job: Optional[shared_remixjob.RemixJob] = dataclasses.field(default=None)
    r"""A Remix request object."""
    