"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import controlentity as shared_controlentity
from typing import Optional


@dataclasses.dataclass
class ControlControllerCreateSecurity:
    
    bearer: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'http', 'sub_type': 'bearer', 'field_name': 'Authorization' }})
    

@dataclasses.dataclass
class ControlControllerCreateRequestBodyFiles:
    
    content: bytes = dataclasses.field(metadata={'multipart_form': { 'content': True }})
    files: str = dataclasses.field(metadata={'multipart_form': { 'field_name': 'files' }})
    

@dataclasses.dataclass
class ControlControllerCreateRequestBody:
    
    files: ControlControllerCreateRequestBodyFiles = dataclasses.field(metadata={'multipart_form': { 'file': True }})
    r"""The image to upload"""
    prompt: str = dataclasses.field(metadata={'multipart_form': { 'field_name': 'prompt' }})
    r"""A text prompt explaining what the generated image should look like."""
    mode: Optional[str] = dataclasses.field(default=None, metadata={'multipart_form': { 'field_name': 'mode' }})
    r"""The segmentation mode that should be used when generating the image."""
    negative_prompt: Optional[str] = dataclasses.field(default=None, metadata={'multipart_form': { 'field_name': 'negativePrompt' }})
    r"""A statement explaining what to avoid in the image"""
    number_of_images: Optional[float] = dataclasses.field(default=None, metadata={'multipart_form': { 'field_name': 'numberOfImages' }})
    r"""Number of images to generate"""
    seed: Optional[float] = dataclasses.field(default=None, metadata={'multipart_form': { 'field_name': 'seed' }})
    r"""The seed to use for the random number generator"""
    steps: Optional[float] = dataclasses.field(default=None, metadata={'multipart_form': { 'field_name': 'steps' }})
    r"""How many steps to take"""
    webhook_url: Optional[str] = dataclasses.field(default=None, metadata={'multipart_form': { 'field_name': 'webhookUrl' }})
    r"""An optional URL to ping with the status when the job is finished."""
    

@dataclasses.dataclass
class ControlControllerCreateRequest:
    
    model_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'modelId', 'style': 'simple', 'explode': False }})
    request_body: ControlControllerCreateRequestBody = dataclasses.field(metadata={'request': { 'media_type': 'multipart/form-data' }})
    

@dataclasses.dataclass
class ControlControllerCreateResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    control_entity: Optional[shared_controlentity.ControlEntity] = dataclasses.field(default=None)
    r"""The newly generated image."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    