"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import editentity as shared_editentity
from ..shared import security as shared_security
from typing import Optional


@dataclasses.dataclass
class EditControllerCreateSecurity:
    
    bearer: shared_security.SchemeBearer = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'http', 'sub_type': 'bearer' }})  
    

@dataclasses.dataclass
class EditControllerCreateRequestBodyFiles:
    
    content: bytes = dataclasses.field(metadata={'multipart_form': { 'content': True }})  
    files: str = dataclasses.field(metadata={'multipart_form': { 'field_name': 'files' }})  
    

@dataclasses.dataclass
class EditControllerCreateRequestBody:
    
    files: EditControllerCreateRequestBodyFiles = dataclasses.field(metadata={'multipart_form': { 'file': True }})
    r"""The image to upload"""  
    prompt: str = dataclasses.field(metadata={'multipart_form': { 'field_name': 'prompt' }})
    r"""A statement explaining what edit to perform to the image"""  
    image_guidance_scale: Optional[float] = dataclasses.field(default=None, metadata={'multipart_form': { 'field_name': 'imageGuidanceScale' }})
    r"""How much to weight the image guidance"""  
    seed: Optional[float] = dataclasses.field(default=None, metadata={'multipart_form': { 'field_name': 'seed' }})
    r"""The seed to use for the random number generator"""  
    steps: Optional[float] = dataclasses.field(default=None, metadata={'multipart_form': { 'field_name': 'steps' }})
    r"""How many steps to take"""  
    text_guidance_scale: Optional[float] = dataclasses.field(default=None, metadata={'multipart_form': { 'field_name': 'textGuidanceScale' }})
    r"""How much to weight the text guidance"""  
    webhook_url: Optional[str] = dataclasses.field(default=None, metadata={'multipart_form': { 'field_name': 'webhookUrl' }})
    r"""An optional URL to ping with the status when the edit is complete or failed"""  
    

@dataclasses.dataclass
class EditControllerCreateRequest:
    
    request: EditControllerCreateRequestBody = dataclasses.field(metadata={'request': { 'media_type': 'multipart/form-data' }})  
    security: EditControllerCreateSecurity = dataclasses.field()  
    

@dataclasses.dataclass
class EditControllerCreateResponse:
    
    content_type: str = dataclasses.field()  
    status_code: int = dataclasses.field()  
    edit_entity: Optional[shared_editentity.EditEntity] = dataclasses.field(default=None)
    r"""The newly created edit."""  
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)  
    