"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import trainingsampleentity as shared_trainingsampleentity
from typing import Optional


@dataclasses.dataclass
class SamplesControllerFindOneSecurity:
    
    bearer: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'http', 'sub_type': 'bearer', 'field_name': 'Authorization' }})
    

@dataclasses.dataclass
class SamplesControllerFindOneRequest:
    
    model_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'modelId', 'style': 'simple', 'explode': False }})
    r"""The ID of the model to retrieve."""
    sample_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'sampleId', 'style': 'simple', 'explode': False }})
    r"""The ID of the image sample to retrieve."""
    

@dataclasses.dataclass
class SamplesControllerFindOneResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    training_sample_entities: Optional[list[shared_trainingsampleentity.TrainingSampleEntity]] = dataclasses.field(default=None)
    r"""A specific training sample."""
    