"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import modelversionentity as shared_modelversionentity
from typing import Optional


@dataclasses.dataclass
class VersionsControllerFindAllSecurity:
    
    bearer: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'http', 'sub_type': 'bearer', 'field_name': 'Authorization' }})
    

@dataclasses.dataclass
class VersionsControllerFindAllRequest:
    
    model_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'modelId', 'style': 'simple', 'explode': False }})
    r"""The ID of the model to retrieve."""
    

@dataclasses.dataclass
class VersionsControllerFindAllResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    model_version_entities: Optional[list[shared_modelversionentity.ModelVersionEntity]] = dataclasses.field(default=None)
    r"""A list of all versions of a model."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    